
server:
  port: 8866
  max-http-header-size: 102400

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lsh_reader?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

logging:
  level:
    com.lsh.sp:
      mapper: debug



mybatis:
  configuration:
    #    数据库字段下划线转换成驼峰
    map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml