
server:
  port: 8866

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lsh_reader?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
logging:
  level:
    com.lsh.sp:
      mapper: debug



mybatis:
  configuration:
      #    数据库字段下划线转换成驼峰
    map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml